version: "3.2"

services:
  thingspanel-core:
    image: thingspanel/core:${VERSION}
    container_name: 'thingspanel-core-${VERSION}'
    restart: 'always'
    links:
      - timescaledb
      - rabbitmq
    ports:
      - "${HTTP_PORT}:80"
      - "${TCP_PORT}:9505"
      - "${WEBSOCKET_PORT}:5200"
    volumes:
      - ./conf/core/.env:/var/www/backend/.env
      - ./conf/vue/.env:/var/www/frontend/.env.production
      - ./logs/core:/var/www/backend/storage/logs
      - ./logs/nginx:/var/log/nginx
      - ./logs/supervisor:/var/log/supervisor
      - ./extensions:/var/www/backend/app/Extensions
    privileged: true
    environment:
      - ENV_MODE=${ENV_MODE}
#    entrypoint: /entrypoint.sh
    depends_on:
      - timescaledb
      - rabbitmq
    networks:
      thingspanel-network:
        ipv4_address: 172.41.0.10
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: 'thingspanel-timescaledb-${VERSION}'
    restart: 'always'
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
    networks:
      thingspanel-network:
        ipv4_address: 172.41.0.11
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'thingspanel-rabbitmq-${VERSION}'
    restart: 'always'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "${MQTT_PORT}:1883"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      thingspanel-network:
        ipv4_address: 172.41.0.12
networks:
  thingspanel-network:
    ipam:
      config:
        - subnet: 172.41.0.0/24
